#! /usr/bin/env python
from vector_Space_Model import vector_space_model
from document import document
import os
import sys
import webbrowser

# This version exists so that it can be used quicker after using chmod +x
# For faster use in the terminal


if __name__ == '__main__':
    # Create the vector_space_model class
    vector_space_model = vector_space_model()

    # Build the query as a document
    argument = ""
    for arg in sys.argv[1:]:
        argument += arg + " "
    query_document = document("query", argument)

    # Add that document to the list of documents
    vector_space_model.documents.append(query_document)
    vector_space_model.build_documents()
    vector_space_model.document_length()
    vector_space_model.cosine_similarity()

    # Attempt to open the file in the default viewer
    try:
        webbrowser.open_new_tab("documents/" + vector_space_model.document_return.name)
    except AttributeError:
        print("No match!")
